default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || 'root' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: 3306
  encoding: utf8mb4
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Joeven_development

test:
  <<: *default
  database: Joeven_test

production:
  <<: *default
  database: Joeven_production
  username: Joeven
  password: <%= ENV['JOEVEN_DATABASE_PASSWORD'] %>
